grafana:
  #image: grafana/grafana:6.3.0-beta1
  image: grafana/grafana:6.2.5
  #image: grafana/grafana:5.4.4
  #image: grafana/grafana:4.6.3
  ports:
    - "3001:3000"
  volumes:
    - ./:/var/lib/grafana/plugins/grafana-linechart-panel
    - ./provisioning:/etc/grafana/provisioning
  environment:
    - TERM=linux
